Contents
--------

This part of the documentation, which is mostly prose, begins with some
background information about Clint, then focuses on step-by-step
instructions for using Clint for development.

.. toctree::
   :maxdepth: 2

   foreword
   installation
   useful-tools
   tutorial/index
   templating
   testing
   errorhandling
   config
   signals
   shell
   patterns/index
   deploying/index
   becomingbig


API Documentation
-----------------

   api


Additional Notes
----------------

Contribution notes and legal information are here for the interested.

.. toctree::
   :maxdepth: 2

   contribute
   license